# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16WH26fyHGLBcva8OrSCPFVjRQshkHF5X
"""



def divide(a,b):
    if(b==0):
       print("Syntax Error")
       div=0
    else:
       div=a/b
    return div